### ISSUE TITLE
Security Issue!!! Arbitrary code execution in ASL

### ISSUE THREAD

**Issue by d3m0n-r00t** [JonasFrey96/ASL#1]
Hi,
## Issue Description
Possible arbitrary code execution bug in ```ASL```.

### Please find detailed description and fix here (https://github.com/418sec/ASL/pull/1)

**Comment by d3m0n-r00t** [comment]
@JonasFrey96,
Any thoughts on this???

**Comment by JonasFrey96** [comment]
Thanks. I will fix it with the next commit.

Best Jonas

**Comment by d3m0n-r00t** [comment]
@JonasFrey96 The fix is available in https://github.com/418sec/ASL/pull/1.
@JamieSlome.
